[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

# cache bust: 1

[deploy]
startCommand = "cd /app/backend &&  python manage.py makemigrations account && python manage.py migrate_schemas account --shared && python manage.py migrate_schemas --shared && gunicorn config.wsgi:application --config gunicorn.conf.py"
healthcheckPath = ""