# Generated by Django 5.2.9 on 2026-03-16 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateDim',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_date', models.DateField(unique=True)),
                ('day', models.IntegerField()),
                ('day_name', models.CharField(max_length=20)),
                ('day_of_week', models.IntegerField()),
                ('day_of_year', models.IntegerField()),
                ('week_of_year', models.IntegerField()),
                ('iso_week', models.IntegerField()),
                ('month', models.IntegerField()),
                ('month_name', models.CharField(max_length=20)),
                ('quarter', models.IntegerField()),
                ('year', models.IntegerField()),
                ('is_weekend', models.BooleanField()),
                ('fiscal_month', models.IntegerField()),
                ('fiscal_quarter', models.IntegerField()),
                ('fiscal_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Date Dimension',
                'verbose_name_plural': 'Date Dimensions',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audit.datedim')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Audit Log',
                'verbose_name_plural': 'Security Audit Logs',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audit.datedim')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'indexes': [models.Index(fields=['company'], name='audit_activ_company_45e64c_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_activ_entity__5a526e_idx')],
            },
        ),
    ]
