# Generated by Django 5.2.9 on 2026-03-20 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hris_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('termination_date', models.DateField()),
                ('reason', models.TextField()),
                ('last_working_day', models.DateField()),
                ('is_voluntary', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hris_core.employee')),
            ],
            options={
                'db_table': 'hris_terminations',
            },
        ),
    ]
