# Generated by Django 5.2.9 on 2025-12-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_alter_customuser_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_2fa_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_fa_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_fa_type',
            field=models.CharField(choices=[('AUTHENTICATOR', 'Authenticator'), ('SMS', 'SMS')], default='AUTHENTICATOR', max_length=20),
        ),
    ]
