# Generated by Django 5.2.9 on 2026-03-16 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_parent_company', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logo', verbose_name='Company Logo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Company Address')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('deleted', 'Deleted')], default='active', max_length=20, verbose_name='Status')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='company.company')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(max_length=20)),
                ('default_currency', models.CharField(max_length=10)),
                ('timezone', models.CharField(max_length=50)),
                ('fiscal_year_start_month', models.IntegerField()),
                ('feature_flags', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='company.company')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Companies Settings',
            },
        ),
    ]
