# Generated by Django 5.2.9 on 2026-03-20 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hris_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/%Y/%m/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hris_core.employee')),
            ],
            options={
                'db_table': 'hris_expense_claims',
            },
        ),
    ]
