# Generated by Django 5.2.9 on 2026-03-26 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_core', '0003_employee_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hris_core.department', verbose_name="Bo'lim"),
        ),
    ]
